### ISSUE TITLE
Dask Scheduler PodUnschedulable 

### ISSUE THREAD

**Issue by ohashmi1** [dask/dask-gke#70]
Hi I am trying to create a cluster, however my dask-scheduler is alwasy unschedulable. I have enough resources. I will add my cluster.yaml here. It also has autoscaling enabled but I can't create my cluster.
<img width="982" alt="Screen Shot 2019-10-01 at 9 19 46 AM" src="https://user-images.githubusercontent.com/1936054/65965431-a2a61c80-e42c-11e9-976a-16576332d838.png">

I see this on my kubernetes engine 

<img width="649" alt="Screen Shot 2019-10-01 at 9 20 42 AM" src="https://user-images.githubusercontent.com/1936054/65965566-cff2ca80-e42c-11e9-9aef-fc8ca7d4e05b.png">

**Comment by mrocklin** [comment]
This project is no longer maintained.  We recommend using the approaches
mentioned in https://docs.dask.org/en/latest/setup/cloud.html
